### ISSUE TITLE
computed values won't reflect on data.literals

### ISSUE THREAD

**Issue by msant77** [marcosantana77/vuejs-brainstorm#1]
```
new Vue({
  data : {
    someCondition : true, 
    someValue : this.someCondition ? 'ifTrue' : 'ifFalse'
  }
})
```
`someValue` will never change, even if `someCondition` changes

Does anyone knows why ?

**Comment by cfernandomaciel** [comment]
I believe for that, you'll need to use props. But I'm not able to send any working example right now. 

But anyways, it's should look like this:
```
Vue.component('example', {
  props: {
   
    propCondition: {
      someValue: function (condition) {
        return (condition) ? "ifTrue": "ifFalse"
      }
    }
  }
})
```

Look after props, the answer might be there

**Comment by msant77** [comment]
Beautiful. I am going to implement this one after going through the next two chapters which seems to address this issue

**Comment by msant77** [comment]
Computed Properties is the feature that fixes this situation: 
```
new Vue({
  data : {
    someCondition : true 
  }, 
  computed: {
    someValue() {return this.someCondition ? 'ifTrue' : 'ifFalse'}
  }
})
```
